### ISSUE TITLE
1-5 of 5 errors: 4;4;4;4;4

### ISSUE THREAD

**Issue by ianchanning** [SublimeLinter/SublimeLinter-phpmd#8] opened 2015-09-04 10:20 UTC
I'm on Windows 8.1 64-bit and I'm using Sublime Text 3 Build 3083.

At the top of all of my PHP files I have the following error listed:

`1-5 of 5 errors: 4;4;4;4;4, Line 2, Column 1` even if the file just contains

```php
<?php

```
and nothing else. If I go into my SublimeLinter.sublime-settings file and disable phpmd e.g. 

```json
            "phpmd": {
                "@disable": true,
                "args": [],
                "excludes": [],
                "rulesets": "cleancode,codesize,naming,controversial,design,unusedcode"
            }
```

Then the errors go away.

**Comment by ajmichels** [comment] 2016-03-13 23:50
If you are still getting this error can you turn on [debug mode](http://www.sublimelinter.com/en/latest/troubleshooting.html#debug-mode) and provide the output?

**Comment by ianchanning** [comment] 2016-03-14 10:16
It looks like the error has gone.

I'm currently on Sublime Text 3 Build 3103.

**Comment by ianchanning** [comment] 2016-03-14 10:28
Sorry - I thought the error was gone but that's purely because I'd stopped using it an removed it.

I still need to do further testing to check that the error is there.

**Comment by ajmichels** [comment] 2016-03-18 03:31
I can't seem to reproduce this so if you can provide the debug output it would be really helpful.

**Comment by ajmichels** [comment] 2016-10-13 17:11
Closing this because I haven't received anymore information from the submitter.

**Closed by ajmichels** 2016-10-13 17:11 UTC
Labels: bug, waiting
